# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Investment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Investment

  pod 'IQKeyboardManagerSwift', '~> 6.0.0'
  pod 'MaterialComponents/TextFields'
  pod 'TextFieldEffects'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.3'


  target 'InvestmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvestmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
